docs: add ARC-1 proposal
axelarnetwork/arcs pull request #1
Opened 2024-12-04 16:51 UTC by milapsheth

2024-12-05 17:15 UTC, cjcobb23 commented on ARCS/arc-1.md
> +    bytes32 tokenId;
How/when is the token id generated?

2024-12-05 17:16 UTC, cjcobb23 commented on ARCS/arc-1.md
> +}
So just to confirm, these are the exact messages the ITS hub will receive?

2024-12-05 20:55 UTC, cjcobb23 commented on ARCS/arc-1.md
> +    bytes destinationToken;
Are these addresses?

2024-12-06 15:01 UTC, haiyizxx commented on ARCS/arc-1.md
> +    bytes params;
could you explain what are `sourceToken`, `destinationToken` and `params`?

2024-12-06 15:09 UTC, haiyizxx commented on ARCS/arc-1.md
> +4. User calls `linkToken` on ITS Chain A with the destination token address for Chain B. This submits a `LinkToken` msg type to ITS Hub.
Users now need to register and link a token. Could the linking process get stuck due to user input errors? If so, what’s the mechanism to resolve it?

2024-12-06 19:02 UTC, fish-sammy requested changes

2024-12-06 19:02 UTC, fish-sammy commented on ARCS/arc-1.md
> +5. ITS Hub intercepts the `LinkToken` msg. It reads the decimals for each token address from it’s storage to calculate the scaling factor and creates the TokenInstance. If a token address isn’t regis
Again, we don't calculate any scaling factor. We only store the decimals and that is good enough.

2024-12-06 19:02 UTC, fish-sammy commented on ARCS/arc-1.md
> +6. ITS Chain B receives the `LinkToken` msg. It deploys the corresponding token manager for the token to set it up.
What does the manager do? when's chain A's token manager deployed?

2024-12-06 19:02 UTC, fish-sammy commented on ARCS/arc-1.md
> +- Solution 2 introduces an additional step, but is more robust against errors
Much prefer 2, but it needs to be polished.

2024-12-06 20:19 UTC, cjcobb23 commented on ARCS/arc-1.md
> +    bytes tokenAddress;
I thought so too, but apparently there is no way to consistently generate token ids across chains. We should specify that constraint in this spec @milapsheth

2024-12-06 20:21 UTC, cjcobb23 commented on ARCS/arc-1.md
> +4. User calls `linkToken` on ITS Chain A with the destination token address for Chain B. This submits a `LinkToken` msg type to ITS Hub.
that's actually a good question, why not allow people to link tokens directly from axelar? The command could even take a list of token addresses, where an arbitrary number of tokens are linked

2024-12-06 21:42 UTC, cjcobb23 commented on ARCS/arc-1.md
> +    uint256 tokenManagerType;
is this the type used at the destination?

2024-12-06 21:48 UTC, cgorenflo requested changes
Summarizing the changes I'd like to see (overlapping with what others have mentioned):
- provide context for what the token manager does
- explain the choice of data types and make clear if you mean to describe messages that are sent as generic bytes to the hub, where they then get interpreted, or if this is supposed to be the Hub interface on axelarnet
- describe the security assumptions/ who is authorized to send which message

As a discussion piece for the next iteration of the document, I very much prefer option 2 over option 1, but I also have a third suggestion that is tied to a question:
Do links need to be defined 1-to-1? If not, we could have a message `LinkToTokenId` that each token "endpoint" can call to register itself to a specific ID. This ensures that each token can only authorize itself, instead of involving tokens on other chains. In a sense, the token id is the "hub" that each token implementation can link it's spoke to and then interact with each other token that is registered to that token id.
Questions to consider:
- How do we prevent someone from registering some new token with an existing token id ecosystem?
- Do tokens on other chains react to a new token being linked to their token id?

To me, it is still unclear what the detailed basic requirements for token linking are, independent of the solution we choose

2024-12-06 21:48 UTC, cgorenflo commented on ARCS/arc-1.md
> +Setting this incorrectly however can be lead to the ITS hub recording the deployment incorrectly, while the deployment tx on the destination ITS will fail due to mismatching decimals, which isn’t rec
```suggestion
Setting this incorrectly, however, can lead to the ITS hub recording the deployment incorrectly, while the deployment tx on the destination ITS will fail due to mismatching decimals, which isn’t recoverable.
```

2024-12-06 21:48 UTC, cgorenflo commented on ARCS/arc-1.md
> +One potential mitigation is to allow the deployer to resubmit the msg but with a different destination decimals, and have ITS hub overwrite the recorded deployment. ITS Hub can allow this overwrite u
```suggestion
One potential mitigation is to allow the deployer to resubmit the msg but with different destination decimals, and have ITS hub overwrite the recorded deployment. ITS Hub can allow this overwrite until the first Transfer msg is encountered to allow the user to fix their deployment. This adds some more complexity in ITS hub setup.
```

2024-12-06 21:48 UTC, cgorenflo commented on ARCS/arc-1.md
> +    uint256 tokenManagerType;
why does this need to be uint256?

2024-12-06 21:48 UTC, cgorenflo commented on ARCS/arc-1.md
> +}
Is this the generalized interface that all chains need to support? Because in the Hub I would like to have better types to represent this. As an aside, uint256 is not necessarily supported everywhere, is it?

2025-04-21 16:34 UTC, cgorenflo approved these changes

2025-04-21 16:52 UTC, fish-sammy approved these changes

2025-04-23 15:17 UTC, merged